"""Tests for collection rule ordering (mod deploy order + plugin load order)."""
from utils import vortex_loadorder as lo


# --- generic toposort -----------------------------------------------------
def test_stable_toposort_respects_edges_and_is_stable():
    nodes = ["a", "b", "c", "d"]
    # c must come before a; ties break by original index, so once c frees a,
    # a (index 0) is emitted ahead of the still-waiting d (index 3).
    assert lo.stable_toposort(nodes, [("c", "a")]) == ["b", "c", "a", "d"]
    # the only hard constraint is satisfied
    out = lo.stable_toposort(nodes, [("c", "a")])
    assert out.index("c") < out.index("a")


def test_stable_toposort_tolerates_cycles():
    out = lo.stable_toposort(["a", "b"], [("a", "b"), ("b", "a")])
    assert sorted(out) == ["a", "b"]   # no crash, all present


# --- mod rules -> deploy order --------------------------------------------
MODS = [
    {"name": "Berries", "source": {"modId": 69415, "md5": "AAA",
                                   "logicalFilename": "Snow Berries"}},
    {"name": "Mari", "source": {"modId": 45952, "md5": "BBB",
                                "logicalFilename": "Mari's flora"}},
]
FOLDERS = {"69415": ["Berries-69415-1"], "45952": ["Mari-45952-1"]}


def test_order_mods_after_rule_puts_source_last():
    # rule: Berries (source) loads AFTER Mari (reference) -> Berries wins -> last
    rules = [{"type": "after",
              "source": {"fileMD5": "aaa"}, "reference": {"fileMD5": "bbb"}}]
    resolve = lo.build_mod_resolver(MODS, FOLDERS)
    order = lo.order_mods(["Berries-69415-1", "Mari-45952-1"], rules, resolve)
    assert order.index("Mari-45952-1") < order.index("Berries-69415-1")


def test_resolver_matches_by_md5_then_logical():
    resolve = lo.build_mod_resolver(MODS, FOLDERS)
    assert resolve({"fileMD5": "aaa"}) == "Berries-69415-1"
    assert resolve({"logicalFileName": "Mari's flora"}) == "Mari-45952-1"
    assert resolve({"fileExpression": "Some-Folder-1-2"}) == "Some-Folder-1-2"
    assert resolve({"fileMD5": "nope"}) is None


# --- plugin master detection + ordering -----------------------------------
def test_is_master_block_by_extension():
    assert lo.is_master_block("X.esm") and lo.is_master_block("Y.esl")
    assert not lo.is_master_block("Z.esp")


def test_is_vanilla_master():
    assert lo.is_vanilla_master("Skyrim.esm")
    assert lo.is_vanilla_master("ccBGSSSE002-ExoticArrows.esl")
    assert not lo.is_vanilla_master("MyMod.esp")


def test_order_plugins_masters_first_then_after_rules():
    plugins = ["B.esp", "A.esp", "Base.esm"]
    after = {"a.esp": ["b.esp"]}   # A loads after B
    out = lo.order_plugins(plugins, lo.is_master_block, after)
    assert out[0] == "Base.esm"                       # master block first
    assert out.index("B.esp") < out.index("A.esp")    # after-rule honored


def test_order_plugins_drops_cross_block_after_edges():
    # an esp cannot be ordered before a master; edge is dropped, masters stay first
    plugins = ["Master.esm", "Plugin.esp"]
    after = {"master.esm": ["plugin.esp"]}
    out = lo.order_plugins(plugins, lo.is_master_block, after)
    assert out == ["Master.esm", "Plugin.esp"]


# --- file rendering (exact Vortex format) ---------------------------------
def test_render_loadorder_format():
    txt = lo.render_loadorder(["Skyrim.esm", "MyMod.esp"])
    assert txt == "# Automatically generated by Vortex\nSkyrim.esm\nMyMod.esp\n"


def test_render_plugins_txt_format():
    txt = lo.render_plugins_txt(["MyMod.esp", "Off.esp"],
                                {"mymod.esp": True, "off.esp": False})
    lines = txt.splitlines()
    assert lines[0].startswith("# This file is used by Skyrim")
    assert "*mymod.esp" in lines      # enabled -> * and lowercased
    assert "off.esp" in lines         # disabled -> no *
